name: Build and Deploy Documentation
on:
    workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4.2.0
            - name: Install uv
              run: pipx install uv
            - name: Setup Python
              uses: actions/setup-python@v5.2.0
              with:
                python-version: '3.10'
            - name: Install Dependencies
              run: uv sync
            - name: Build Documentation
              run: uv run mkdocs build
            - name: Push Documentation to GitHub Pages
              run: |
                uv run mkdocs gh-deploy --clean
