name: Build and Deploy Documentation
on:
    workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4.2.0
            - name: Install poetry
              run: pipx install poetry
            - name: Setup Python
              uses: actions/setup-python@v5.2.0
              with:
                python-version: '3.10'
                cache: "poetry"
            - name: Install Dependencies
              run: poetry install --with dev --all-extras
            - name: Build Documentation
              run: mkdocs build
            - name: Push Documentation to GitHub Pages
              run: |
                mkdocs gh-deploy --clean
